apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: demo
  environment: prd
namePrefix: prd-
namespace: demo
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
    path: config-map.yaml
