apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: demo
build:
  tagPolicy:
    inputDigest: {}
    # sha256: {}
  artifacts:
    - context: .
      image: k8s/demo
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
deploy:
  kubectl: {}
  statusCheck: false
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - deployment/overlays/development
  - name: stg
    manifests:
      kustomize:
        paths:
          - deployment/overlays/staging
  - name: prd
    manifests:
      kustomize:
        paths:
          - deployment/overlays/production
