apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: demo
  environment: local
namespace: demo
resources:
  - config-map.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
