apiVersion: v1
kind: Service
metadata:
  name: demo-loadbalancer-svc
  namespace: demo
spec: 
  type: LoadBalancer
  selector:
    app: demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000